import { Customer, Order, Product, Supplier } from "./types";

export const suppliers: Supplier[] = [
  { id: "sup-1", name: "ABC Fashion Co." },
  { id: "sup-2", name: "Best Apparel Ltd." },
  { id: "sup-3", name: "Trendy Wear Inc." },
  { id: "sup-4", name: "Urban Threads" },
  { id: "sup-5", name: "Coastal Garments" },
];

export const customers: Customer[] = [
  { id: "cus-1", name: "John Trading Co." },
  { id: "cus-2", name: "Global Retailers" },
  { id: "cus-3", name: "Mike Imports" },
  { id: "cus-4", name: "Retail Hub" },
  { id: "cus-5", name: "Skyline Stores" },
];

export const products: Product[] = [
  {
    id: "prd-1",
    name: "Short sleeve cotton t-shirt",
    marka: "MARKA-1",
    photo: "👕",
    defaultDim: "32 × 24 × 18 cm",
  },
  {
    id: "prd-2",
    name: "Denim jacket",
    marka: "MARKA-2",
    photo: "🧥",
    defaultDim: "40 × 30 × 20 cm",
  },
  {
    id: "prd-3",
    name: "Hoodie fleece",
    marka: "MARKA-3",
    photo: "🧥",
    defaultDim: "28 × 20 × 15 cm",
  },
  {
    id: "prd-4",
    name: "Cargo pants",
    marka: "MARKA-4",
    photo: "👖",
    defaultDim: "30 × 22 × 16 cm",
  },
  {
    id: "prd-5",
    name: "Beanie cap",
    marka: "MARKA-5",
    photo: "🧢",
    defaultDim: "18 × 14 × 10 cm",
  },
];

export const paymentAgents: { id: string; name: string }[] = [
  { id: "pa-1", name: "Alipay Agent A" },
  { id: "pa-2", name: "WeChat Pay Agent B" },
  { id: "pa-3", name: "Bank Wire Agent C" },
  { id: "pa-4", name: "Hawala Agent D" },
];

export const initialOrders: Order[] = [
  {
    id: "ord-25-301",
    number: "25-301",
    date: "2025-05-23",
    paymentBy: "pa-1",
    wechatId: "abc.fashion88",
    status: "draft",
    lines: [
      {
        id: "ln-1",
        supplierId: "sup-1",
        picDim: "32 × 24 × 18 cm",
        productId: "prd-1",
        marka: "MARKA-1",
        details: "Short sleeve cotton t-shirt",
        totalCtns: 10,
        pcsPerCtn: 100,
        rmbPerPcs: 12.5,
        customerId: "cus-1",
      },
      {
        id: "ln-2",
        supplierId: "sup-2",
        picDim: "40 × 30 × 20 cm",
        productId: "prd-2",
        marka: "MARKA-2",
        details: "Denim jacket",
        totalCtns: 5,
        pcsPerCtn: 50,
        rmbPerPcs: 45,
        customerId: "cus-2",
      },
      {
        id: "ln-3",
        supplierId: "sup-3",
        picDim: "28 × 20 × 15 cm",
        productId: "prd-3",
        marka: "MARKA-3",
        details: "Hoodie fleece",
        totalCtns: 8,
        pcsPerCtn: 60,
        rmbPerPcs: 38,
        customerId: "cus-3",
      },
    ],
  },
  {
    id: "ord-25-300",
    number: "25-300",
    date: "2025-05-22",
    paymentBy: "pa-2",
    wechatId: "best.apparel",
    status: "saved",
    lines: [
      {
        id: "ln-4",
        supplierId: "sup-2",
        picDim: "36 × 28 × 18 cm",
        productId: "prd-4",
        marka: "MARKA-4",
        details: "Cargo pants",
        totalCtns: 12,
        pcsPerCtn: 80,
        rmbPerPcs: 22,
        customerId: "cus-2",
      },
      {
        id: "ln-5",
        supplierId: "sup-4",
        picDim: "20 × 15 × 12 cm",
        productId: "prd-5",
        marka: "MARKA-5",
        details: "Beanie cap",
        totalCtns: 20,
        pcsPerCtn: 100,
        rmbPerPcs: 9.5,
        customerId: "cus-2",
      },
    ],
  },
  {
    id: "ord-25-299",
    number: "25-299",
    date: "2025-05-21",
    paymentBy: "pa-3",
    wechatId: "trendy.wear.co",
    status: "saved",
    lines: [
      {
        id: "ln-6",
        supplierId: "sup-3",
        picDim: "28 × 20 × 15 cm",
        productId: "prd-3",
        marka: "MARKA-3",
        details: "Hoodie fleece",
        totalCtns: 7,
        pcsPerCtn: 60,
        rmbPerPcs: 38,
        customerId: "cus-3",
      },
      {
        id: "ln-7",
        supplierId: "sup-1",
        picDim: "32 × 24 × 18 cm",
        productId: "prd-1",
        marka: "MARKA-1",
        details: "Short sleeve cotton t-shirt",
        totalCtns: 15,
        pcsPerCtn: 100,
        rmbPerPcs: 12.5,
        customerId: "cus-3",
      },
    ],
  },
  {
    id: "ord-25-298",
    number: "25-298",
    date: "2025-05-20",
    paymentBy: "pa-1",
    wechatId: "abc.fashion88",
    status: "saved",
    lines: [
      {
        id: "ln-8",
        supplierId: "sup-1",
        picDim: "32 × 24 × 18 cm",
        productId: "prd-1",
        marka: "MARKA-1",
        details: "Short sleeve cotton t-shirt",
        totalCtns: 6,
        pcsPerCtn: 100,
        rmbPerPcs: 12.5,
        customerId: "cus-4",
      },
    ],
  },
  {
    id: "ord-25-297",
    number: "25-297",
    date: "2025-05-19",
    paymentBy: "pa-4",
    wechatId: "best.apparel",
    status: "saved",
    lines: [
      {
        id: "ln-9",
        supplierId: "sup-2",
        picDim: "40 × 30 × 20 cm",
        productId: "prd-2",
        marka: "MARKA-2",
        details: "Denim jacket",
        totalCtns: 9,
        pcsPerCtn: 50,
        rmbPerPcs: 45,
        customerId: "cus-1",
      },
      {
        id: "ln-10",
        supplierId: "sup-5",
        picDim: "36 × 28 × 18 cm",
        productId: "prd-4",
        marka: "MARKA-4",
        details: "Cargo pants",
        totalCtns: 14,
        pcsPerCtn: 80,
        rmbPerPcs: 22,
        customerId: "cus-1",
      },
    ],
  },
  {
    id: "ord-25-296",
    number: "25-296",
    date: "2025-05-18",
    paymentBy: "pa-2",
    wechatId: "trendy.wear.co",
    status: "saved",
    lines: [
      {
        id: "ln-11",
        supplierId: "sup-3",
        picDim: "28 × 20 × 15 cm",
        productId: "prd-3",
        marka: "MARKA-3",
        details: "Hoodie fleece",
        totalCtns: 10,
        pcsPerCtn: 60,
        rmbPerPcs: 38,
        customerId: "cus-2",
      },
    ],
  },
  {
    id: "ord-25-295",
    number: "25-295",
    date: "2025-05-17",
    paymentBy: "pa-3",
    wechatId: "urban.threads",
    status: "saved",
    lines: [
      {
        id: "ln-12",
        supplierId: "sup-4",
        picDim: "20 × 15 × 12 cm",
        productId: "prd-5",
        marka: "MARKA-5",
        details: "Beanie cap",
        totalCtns: 22,
        pcsPerCtn: 100,
        rmbPerPcs: 9.5,
        customerId: "cus-5",
      },
    ],
  },
  {
    id: "ord-25-294",
    number: "25-294",
    date: "2025-05-16",
    paymentBy: "pa-1",
    wechatId: "abc.fashion88",
    status: "saved",
    lines: [
      {
        id: "ln-13",
        supplierId: "sup-1",
        picDim: "32 × 24 × 18 cm",
        productId: "prd-1",
        marka: "MARKA-1",
        details: "Short sleeve cotton t-shirt",
        totalCtns: 8,
        pcsPerCtn: 100,
        rmbPerPcs: 12.5,
        customerId: "cus-4",
      },
    ],
  },
];

export const formatCNY = (n: number) =>
  "¥ " +
  n.toLocaleString("en-US", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });

export const formatDate = (iso: string) => {
  const d = new Date(iso);
  return d.toLocaleDateString("en-US", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });
};
